### ISSUE TITLE
Where should .bib exist in this REMARK repo?

### ISSUE THREAD

**Issue by MridulS** [econ-ark/REMARK#82]
The BibTeX entry could be of the REMARK or of the original paper.

IMO if a BibTeX entry exists it should exist inside the REMARK itself rather than here (the REMARKs index).

@llorracc Thoughts?

**Comment by llorracc** [comment]
Good question, made more complicated by the fact that the REMARK itself needs to be able to have an independent bibfile of its own.  So, I think we need to require that there should be two bib or CFF files.  Maybe they should be in an "About-Metadata" directory.  If REMARKname is the name of the remark, then one of them should be [REMARKname].bib, like CGMPortfolio.bib.  The other should be a bibtex cite handle for the paper being referenced, like blanchardAEA.bib for the Blanchard presidential address.

Ideally there should be both CFF and bib files.  But, because CFF is a new format designed explicitly to handle online content in a machine-readable way, I think we should require a CFF file for the REMARK itself, and a bib file for the paper being replicated.  A bib file for the REMARK itself is optional, and a CFF for the referenced paper is optional.

**Comment by MridulS** [comment]
Yeah both of them can live in the REMARK itself.
@llorracc I have started building up the template at https://github.com/econ-ark/REMARK-template , we should finalise the required/optional structure of REMARK out there.
